name: Netlify Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with: 
          node-version: 12.x
      - run: npm run patch:npmDownGrade
      - run: npm install
      - run: npm audit fix
      - run: npm run patch:graceful-fs
      - run: npm run cmd:install
      - run: npm run cmd:build
      - run: npm run patch:plugin
      - run: npm run patch:deleteNoUseFiles

      - run: npx netlify-cli deploy --prod --dir=./_book
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
